<a href="https://colab.research.google.com/github/McKendreevv/Mis433/blob/main/In_Class_data_summarization_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise: Data Summarization

In [1]:
import pandas as pd
import numpy as np

In [3]:
pip install nycflights13

Collecting nycflights13
  Downloading nycflights13-0.0.3.tar.gz (8.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 54.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from nycflights13) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->nycflights13) (1.17.0)
Building wheels for collected packages: nycflights13
  Building wheel for nycflights13 (setup.py) ... done
  Created wheel for nycflights13: filename=nycflights13-0.0.3-py3-none-any.whl size=8732722 sha256=5db35a885d878317607a96df7fd202f3af83673b3233a1df97e4d905c2d42163
  Stored in directory: /root/.cache/pip/wheels/58/ee/20/7838832df5510701439239ec10c2d8927de32aac2729ce2085
Successfully built nycflights13
Installing collected packages: nycflights13
Successfully installed nycflights13-0.0.3

In [4]:
from nycflights13 import flights
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

## DataFrame with columns

- year,month,day
        Date of departure    
- dep_time,arr_time
        Actual departure and arrival times (format HHMM or HMM), local tz.
- sched_dep_time,sched_arr_time
        Scheduled departure and arrival times (format HHMM or HMM), local tz.    
- dep_delay,arr_delay
        Departure and arrival delays, in minutes. Negative times represent early departures/arrivals.
- hour,minute
        Time of scheduled departure broken into hour and minutes.
- carrier
        Two letter carrier abbreviation. See airlines() to get name
- tailnum
        Plane tail number
- flight
        Flight number
- origin,dest
        Origin and destination. See airports() for additional metadata.
- air_time
        Amount of time spent in the air, in minutes
- distance
        Distance between airports, in miles
- time_hour
        Scheduled date and hour of the flight as a date. Along with origin, can be used to join flights data to weather data.

In [5]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   year            336776 non-null  int64
 1   month           336776 non-null  int64
 2   day             336776 non-null  int64
 3   dep_time        328521 non-null  float64
 4   sched_dep_time  336776 non-null  int64
 5   dep_delay       328521 non-null  float64
 6   arr_time        328063 non-null  float64
 7   sched_arr_time  336776 non-null  int64
 8   arr_delay       327346 non-null  float64
 9   carrier         336776 non-null  object
 10  flight          336776 non-null  int64
 11  tailnum         334264 non-null  object
 12  origin          336776 non-null  object
 13  dest            336776 non-null  object
 14  air_time        327346 non-null  float64
 15  distance        336776 non-null  int64
 16  hour            336776 non-null  int64
 17  minute          336776 non-null  int64
 18  time_hour       336776 non-null  object
dtypes: float64(5), int64(9), object(5)
memory usage: 48.8+ MB

## Exercises

Write Python scripts to answer the following questions.

In [13]:
# How many distinct airplanes are there in this dataset?
flights['tailnum'].nunique()

4043

In [17]:
# Which hours of the day are the busiest?
# List the top 5 hours with the most flights.
flights.groupby(['hour']).value_counts().head(5)

hour  year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  sched_arr_time  arr_delay  carrier  flight  tailnum  origin  dest  air_time  distance  minute  time_hour
0.0   2013  1      2    42.0      2359            43.0       518.0     442              36.0      B6       707     N580JB   JFK     SJU   189.0     1598      59      2013-01-03T04:00:00Z    1
                   3    32.0      2359            33.0       504.0     442              22.0      B6       707     N763JB   JFK     SJU   193.0     1598      59      2013-01-04T04:00:00Z    1
                        50.0      2145            185.0      203.0     2311             172.0     B6       104     N329JB   JFK     BUF   58.0      301       45      2013-01-04T02:00:00Z    1
                   4    25.0      2359            26.0       505.0     442              23.0      B6       707     N554JB   JFK     SJU   194.0     1598      59      2013-01-05T04:00:00Z    1
                   5    14.0      2359            15.0       503.0     445              18.0      B6       739     N592JB   JFK     PSE   201.0     1617      59      2013-01-06T04:00:00Z    1
                                                                                                                                                                                             ..
24.0  2013  12     9    2400.0    2250            70.0       59.0      2356             63.0      B6       1816    N187JB   JFK     SYR   41.0      209       50      2013-12-10T03:00:00Z    1
                                  2359            1.0        432.0     440             -8.0       B6       1503    N705JB   JFK     SJU   195.0     1598      59      2013-12-10T04:00:00Z    1
                   13   2400.0    2359            1.0        432.0     440             -8.0       B6       1503    N587JB   JFK     SJU   192.0     1598      59      2013-12-14T04:00:00Z    1
                   19   2400.0    2359            1.0        434.0     440             -6.0       B6       1503    N561JB   JFK     SJU   193.0     1598      59      2013-12-20T04:00:00Z    1
                   29   2400.0    1700            420.0      302.0     2025             397.0     AA       2379    N3GMAA   LGA     MIA   161.0     1096      0       2013-12-29T22:00:00Z    1
Name: count, Length: 327346, dtype: int64

In [24]:
# Find all flights (identified by 'carrier' and 'flight')
# that always depart at least 60 minutes late.
flights.groupby(['carrier', 'flight']).agg({'dep_delay': 'min'})

                dep_delay
carrier flight
9E      2900        -13.0
        2901        -10.0
        2902        -17.0
        2903         -7.0
        2904        -11.0
...                   ...
YV      3778         -9.0
        3788        -12.0
        3790          0.0
        3791         -6.0
        3799        168.0

[5725 rows x 1 columns]

In [25]:
# How many flights always depart at least 60 minutes late?
df1 = flights.groupby(['carrier', 'flight']).agg({'dep_delay': 'min'})
df1[df1.dep_delay>=60]

                dep_delay
carrier flight
9E      3283        104.0
        3297        120.0
        3546         64.0
        3583         95.0
        3588        115.0
        3682         66.0
        3760        217.0
B6      205          82.0
DL      390         334.0
        462         125.0
        809         298.0
        917         157.0
        2390         92.0
EV      4151         67.0
        4320         95.0
        4564         91.0
        4617        128.0
        5015         63.0
        5062        111.0
        5071         92.0
        5083         98.0
        5117        219.0
        5294        192.0
        5358         78.0
        5409         87.0
        5425         62.0
        5478        242.0
        5629         71.0
        5668        106.0
        5839         65.0
        5855        209.0
        6082        153.0
        6093        128.0
F9      2001         65.0
OO      8500         67.0
UA      18           95.0
        125          89.0
        348          93.0
        546          60.0
        640         115.0
        945          62.0
        993          69.0
        1510        278.0
US      1226        147.0
WN      217         195.0
        521         346.0
        718          78.0
        1019        203.0
        2521         79.0
        2529         75.0
        3032         90.0
        3791        151.0
YV      3799        168.0

In [39]:
from numpy._core.fromnumeric import shape
# Find all United Airlines (UA) flights (identified by 'carrier' and 'flight')
# that depart (at least) 60 minutes late.
flights[flights.carrier == 'UA'].groupby(['carrier', 'flight']).agg({'dep_delay': 'min'}).shape[0]

1285

In [38]:
# How many United Airlines (UA) flights depart (at least) 60 minutes late?
flights[flights.carrier == 'UA'].groupby(['carrier', 'flight']).agg({'dep_delay': 'min'}).query('dep_delay>=60').shape[0]

8

In [44]:
# Which flights that always arrived on time in December?
flights[flights.carrier == 'UA'].groupby(['carrier', 'flight']).agg({'dep_delay': 'max'}).query('dep_delay<=0')

                dep_delay
carrier flight
UA      16            0.0
        19           -6.0
        39           -1.0
        42           -8.0
        49           -6.0
        52           -7.0
        65            0.0
        85           -5.0
        99           -3.0
        100           0.0
        104          -2.0
        149          -3.0
        366          -6.0
        644          -2.0
        648          -2.0
        672          -1.0
        702           0.0
        716          -2.0
        739          -5.0
        748          -5.0
        796          -1.0
        800           0.0
        805          -2.0
        822         -10.0
        825          -5.0
        829           0.0
        859           0.0
        862          -2.0
        871          -4.0
        895           0.0
        904          -1.0
        906          -2.0
        919           0.0
        926          -4.0
        931          -1.0
        935          -6.0
        944          -5.0
        950          -5.0
        962          -2.0
        966           0.0
        969          -2.0
        971          -3.0
        1032         -1.0
        1095         -4.0
        1096         -1.0
        1173         -2.0
        1185         -2.0
        1234         -2.0
        1434          0.0
        1457         -2.0
        1486         -1.0
        1509          0.0
        1546          0.0
        1577          0.0
        1610         -9.0
        1720         -2.0

In [43]:
# How many flights always arrived on time in December?
flights[flights.carrier == 'UA'].groupby(['carrier', 'flight']).agg({'dep_delay': 'max'}).query('dep_delay<=0').shape[0]

56

In [47]:
# Create a dataframe 'cancelled' for all cancelled flights.
# Assumption: flights that are not cancelled should have values for dep_time.
df2 = flights[flights.dep_time.isna()]
df2.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
838,2013,1,1,NaN,1630,NaN,NaN,1815,NaN,EV,4308,N18120,EWR,RDU,NaN,416,NaN,30,2013-01-01T21:00:00Z
839,2013,1,1,NaN,1935,NaN,NaN,2240,NaN,AA,791,N3EHAA,LGA,DFW,NaN,1389,NaN,35,2013-01-02T00:00:00Z
840,2013,1,1,NaN,1500,NaN,NaN,1825,NaN,AA,1925,N3EVAA,LGA,MIA,NaN,1096,NaN,0,2013-01-01T20:00:00Z
841,2013,1,1,NaN,600,NaN,NaN,901,NaN,B6,125,N618JB,JFK,FLL,NaN,1069,NaN,0,2013-01-01T11:00:00Z
1777,2013,1,2,NaN,1540,NaN,NaN,1747,NaN,EV,4352,N10575,EWR,CVG,NaN,569,NaN,40,2013-01-02T20:00:00Z

In [49]:
# Look at the number of cancelled flights per day.
# Find the top 10 days with the most cancelled flights.
df2[['year','month','day']].value_counts().head(10)

year  month  day
2013  2      8      472
             9      393
      5      23     221
      12     10     204
      9      12     192
      3      6      180
             8      180
      12     5      158
             14     125
      6      28     123
Name: count, dtype: int64

In [53]:
# Which carrier has the worst average arrival delay?
flights.groupby('carrier').agg({'arr_delay':'mean'}).sort_values('arr_delay').tail(1)

         arr_delay
carrier
F9       21.920705

In [62]:
# Which plane (tailnum) has the worst on-time record?
df1 = flights.groupby('tailnum').agg({'arr_delay':['mean','min','max']})
df1.columns = ['ad_mean','ad_min','ad_max']
df1[df1.ad_mean.notna()].sort_values('ad_min')

            ad_mean  ad_min  ad_max
tailnum
N843VA    -5.361111   -86.0   205.0
N840VA    -3.473118   -79.0   354.0
N851UA     5.241379   -75.0   363.0
N3KCAA     3.343284   -75.0   214.0
N551AS   -12.045455   -74.0    95.0
...             ...     ...     ...
N851NW   219.000000   219.0   219.0
N587NW   264.000000   264.0   264.0
N922EV   276.000000   276.0   276.0
N911DA   294.000000   294.0   294.0
N844MH   320.000000   320.0   320.0

[4037 rows x 3 columns]

In [63]:
# What time (hour) of day should you fly if you want to avoid delays as much as possible?
flights.groupby('hour').agg({'dep_delay':['mean','min','max']})

       dep_delay
            mean    min     max
hour
0.0   128.642452    2.0   602.0
1.0   207.049327   61.0   589.0
2.0   239.921875  121.0   471.0
3.0   304.727273  184.0   503.0
4.0    -5.554098  -15.0    -1.0
5.0    -4.355644  -21.0    47.0
6.0    -1.520552  -19.0  1301.0
7.0     0.223289  -26.0   896.0
8.0     1.091432  -18.0  1005.0
9.0     4.268295  -24.0   899.0
10.0    5.548644  -22.0   800.0
11.0    5.652309  -22.0  1126.0
12.0    7.601892  -20.0   419.0
13.0    9.380639  -23.0   415.0
14.0    8.090381  -32.0  1137.0
15.0   10.682049  -22.0   580.0
16.0   13.621150  -24.0   502.0
17.0   16.756593  -27.0   510.0
18.0   18.664671  -21.0   599.0
19.0   21.497342  -30.0   786.0
20.0   28.266213  -43.0   702.0
21.0   42.064964  -23.0   653.0
22.0   68.190042  -22.0   898.0
23.0   96.946865  -18.0   911.0
24.0   64.862069    1.0   420.0

In [64]:
# For each destination, compute the total minutes of arrival delay.
flights.groupby('dest').agg({'arr_delay':'sum'})

      arr_delay
dest
ABQ      1113.0
ACK      1281.0
ALB      6018.0
ANC       -20.0
ATL    190260.0
...         ...
TPA     54749.0
TUL      9896.0
TVC      1232.0
TYS     13912.0
XNA      7406.0

[105 rows x 1 columns]

In [67]:
# Find the worst days in terms of average arrival delay greater than 1 hour.
flights.groupby(['year','month','day']).agg({'arr_delay':'mean'}).query('arr_delay>60').sort_values('arr_delay')

                arr_delay
year month day
2013 5     23   61.970899
     7     22   62.763403
     6     13   63.753689
     3     8    85.862155

In [66]:
# Find the number of carriers between each pair of origin and destination.
flights.groupby(['origin','dest']).agg({'carrier':'count'})

             carrier
origin dest
EWR    ALB       439
       ANC         8
       ATL      5022
       AUS       968
       AVL       265
...              ...
LGA    SYR       293
       TPA      2145
       TVC        77
       TYS       308
       XNA       745

[224 rows x 1 columns]